/*
 * bbepi.allcvs.c
 *
 * This file is automatically generated by the 'contigCVs' script
 * and it contains code for all CVs and TGT export variables.
 *
 * This file is used for the contiguoes download CV copy code and
 * the CV endian conversion code.
 *
 * Generated on Fri Mar 21 10:55:17 PDT 2014
 */

#include "bbepi.global.h"
#include "bbepi.allcv.h"
#include "bbepi.tgtex.h"
