# Makefile generated by imake - do not edit!
# $Xorg: imake.c,v 1.6 2001/02/09 02:03:15 xorgcvs Exp $

#
#
#

# ====================================================================
#
#  Included macros and rules from <Imake.cf> and <Imake.rules>
#
# ====================================================================

PWD        = /home/ysfeng/surbeck/temp/sake
TOP        = /ESE_DV24.0_R01
OS_NAME    = Linux
OS_RELEASE = 2_6_18__194_17_1_el5

SHELL = /bin/sh

BASENAME = /bin/basename
CAT      = /bin/cat
CHMOD    = /bin/chmod
CP       = /bin/cp
CRYPT    = $(TOP)/3p_linux/enigma/bin/enigma
CUT      = /usr/bin/cut
DD       = /bin/dd
GREP     = /bin/grep
MV       = /bin/mv
RM       = /bin/rm -f
SORT     = /bin/sort
TAIL     = /usr/bin/tail
TAR      = /bin/tar
TOUCH    = /bin/touch

# ====================================================================

#
#
#
#
#
#

# ====================================================================
#
#  Common targets found in all makefiles
#
# ====================================================================

all:: hw sim

clean::

hw::

install::

sim::

test::

# ====================================================================

#
#
#
#
#
#

# ====================================================================
#
#  Beginning of included template file: "EPIC.tmpl"
#
# ====================================================================

#
# These are parameter definitions common to all users who use the
#    Epic and Epic+ preprocessors.
#

CREATE_CVCONST_DEFS     = $(TOP)/psd/bin/createCvconstDefs
CREATE_PULSEDEFS        = $(TOP)/psd/bin/createEpicPulsedefs
CREATE_CNV_ENDIAN_INPUT = $(TOP)/psd/bin/createCnvEndianInput
EC                      = $(TOP)/psd/bin/ec
EP_PROCESS              = $(TOP)/psd/bin/processefile
EP_MERGE                = $(TOP)/psd/bin/mergehfiles
EP_BRT                  = $(TOP)/psd/bin/buildruntime
EP_CONTIG               = $(TOP)/psd/bin/contigCVs
EP_LINK                 = $(TOP)/psd/bin/createEpicPlusLinks

ENDIAN_CONVERTER =     $(TOP)/3p/endian_converter/endian_converter

# Locking flag to modify CVs.
# Use -DMCVALL to allow all CVs to be modified.
M_CVS =

#
# These are endian conversion definitions
# The idea is to pass to the endian-converter, the same flags as the
# host-hardware PSD.
#

ENDIAN_CONVERTER_FLAGS =     -m32     $(M_CVS)     -DHOST_TGT     -DMGD_IF     -DLX_ENBLpopup     -DPSD_HW

ENDIAN_EFLAG =

ENDIAN_EPFLAG =     -DEXTERN=extern

#
# End common Epic/Epic+ parameter definitions.
#

# --------------------------------------------------------------------
#
#  Rule: "NoWarnings()"
#
#  This rule is empty for the Epic/Epic+ compilers.  It is only used
#  by the host and target compilers.
#
# --------------------------------------------------------------------

# --------------------------------------------------------------------
#
#  Rule: "StandardSuffixRules()"
#

.SUFFIXES:
.SUFFIXES: .e .epic .epicplus

.e.epic:
	@echo "=========================================================="
	@echo "   Processing $*"
	@echo "=========================================================="

	$(RM) ${@F} $*.host.c $*.tgt.c $*.global.h $*.allcv.h \
		$*.tgtex.h $*.hostdecl.h $*.tgtdecl.h $*.exportstr.h \
		$*.runtime.h $*.ext.h $*.host.map \
		cvinit.in predownload.in

	$(EC) $(PG_FLAG) $(ADD_EFLAGS) $(EPIC_INCLUDES) $<

	$(TOUCH) ${@F}

.e.epicplus:
	@echo "=========================================================="
	@echo "   Processing $*"
	@echo "=========================================================="

	$(RM) ${@F} $*.host.c $*.tgt.c $*.global.h $*.allcv.h \
		$*.tgtex.h $*.hostdecl.h $*.tgtdecl.h $*.exportstr.h \
		$*.runtime.h $*.ext.h $*.host.map \
		cvinit.in predownload.in \
		$*.cvinit.in $*.predownload.in $*.tgt_hdr.h \
		$*.allcv_hwdefs.h $*.allcv_simdefs.h \
		$*.exportstr_hwdefs.h $*.exportstr_simdefs.h \
		$*.hostdecl_hwdefs.h $*.hostdecl_simdefs.h \
		$*.tgtdecl_hwdefs.h $*.tgtdecl_simdefs.h \
		$*.tgtex_hwdefs.h $*.tgtex_simdefs.h $*.tgt_hdr.h

	$(RM) -r $(EPDIR)

	$(EP_PROCESS) $(PSD) $* "$(EP_SIMFLAGS) $(EPIC_INCLUDES)" \
		"$(EP_HWFLAGS) $(EPIC_INCLUDES)" \
		"$(PG_FLAG) $(ADD_EPFLAGS) $(EPIC_INCLUDES)"

	$(TOUCH) $(EPDIR)/$*.tgt_hdr.h

	cd $(EPDIR); $(MV) -f $*.allcv_hwdefs.h $*.allcv_simdefs.h \
		$*.exportstr_hwdefs.h $*.exportstr_simdefs.h \
		$*.hostdecl_hwdefs.h $*.hostdecl_simdefs.h \
		$*.tgtdecl_hwdefs.h $*.tgtdecl_simdefs.h \
		$*.tgtex_hwdefs.h $*.tgtex_simdefs.h $*.tgt_hdr.h \
		$(PWD)

	$(RM) cvinit.in predownload.in

	$(RM) -r $(EPDIR)

	$(TOUCH) ${@F}

# --------------------------------------------------------------------

# --------------------------------------------------------------------
#
#  Rule: "CleanRule()"
#
#
#  Epic+ creates an "EPIC+" subdirectory in the current directory.
#     This rule ensures that "EPIC+" will be removed when the "clean"
#     target is invoked.
#

clean::
	$(RM) -r ./EPIC+

	-$(RM) *.epic *.host.c *.tgt.c *.global.h *.allcv.h \
		*.tgtex.h *.hostdecl.h *.tgtdecl.h *.exportstr.h \
		*.runtime.h *.ext.h *.host.map \
                cvinit.in predownload.in

	-$(RM) *.epicplus *.cvinit.in *.predownload.in *.tgt_hdr.h \
		*.allcv_hwdefs.h *.allcv_simdefs.h \
		*.exportstr_hwdefs.h *.exportstr_simdefs.h \
		*.hostdecl_hwdefs.h *.hostdecl_simdefs.h \
		*.tgtdecl_hwdefs.h *.tgtdecl_simdefs.h \
		*.tgtex_hwdefs.h *.tgtex_simdefs.h *.tgt_hdr.h

# --------------------------------------------------------------------

# ====================================================================
#
#  End of included template file: "EPIC.tmpl"
#
# ====================================================================

#
#
#
#
#
#

# ====================================================================
#
#  Local Imakefile begins here
#
# ====================================================================

TOOLSET = EPIC

MAKE_TARGET = programs

PSD = bbepi

ADD_INLINE_FILES = touch.e

ADD_EFILES =

ADD_CFILES_HOST = getminesp.c

ADD_CFILES_TGT =

ADD_EFLAGS = -z

ADD_E_INCLUDES =

ADD_CFLAGS_HH = -Werror

ADD_CFLAGS_HS = -Werror

ADD_CFLAGS_TH = -Werror

ADD_CFLAGS_TS = -Werror

ADD_LINKFLAGS_HH =

ADD_LINKFLAGS_HS =

ADD_LINKFLAGS_TH =

ADD_LINKFLAGS_TS =

ADD_LIBS_HH =

ADD_LIBS_HS =

ADD_LIBS_TH =

ADD_LIBS_TS =

# --------------------------------------------------------------------
#
#  Rule: "UsePgenOnHost()"
#
#  This rule sets an Epic compiler flag to activate the Pulsegen on
#  the Host feature.  Basically, the Epic preprocessor will put the
#  contents of the @pg section in both the Host and Tgt C sources.
#

PG_FLAG = -P

# --------------------------------------------------------------------

# --------------------------------------------------------------------
#
#  Rule: "PsdParameters()"
#
#

#
#  Rule: "EpicParameters1()"
#

DIR_CVCONST_INCLUDE = $(TOP)/psd/include/private

DIR_EP_FEATURES_INCLUDE = $(TOP)/psd/epicplus_features

EPIC_INCLUDES   = $(ADD_E_INCLUDES) \
                  -I. \
                  -I$(TOP)/psd/include \
                  -I$(TOP)/psd/include/private \
                  -I$(TOP)/psd/psdsource \
                  -I$(TOP)/lx/em/include \
                  -I$(TOP)/lx/include \
                  -I$(TOP)/host/foundation-libs/CnvEndianLib/host_static \
                  -I$(TOP)/host/include \
                  -I$(TOP)/mgd/include \
                  -I$(TOP)/vre/support

EP_SIMFLAGS     = -DINIT \
                  -DEXTERN= \
                  -DINC4CPP \
                  $(M_CVS)

EP_HWFLAGS      = $(EP_SIMFLAGS)

EPDIR           = ./EPIC+

CNV_ENDIAN_FILES = $(PSD).cnvendian.input.c \
                   $(PSD).cnvendian.input.i \
                   $(PSD).cnvendian.private.h \
                   $(PSD).cnvendian.globalvar.h \
                   $(PSD).cnvendian.c \
                   $(PSD).cnvendian.api.h

#
#  Rule: "EpicParameters2()"
#

MERGE_FLAG = 1

# --------------------------------------------------------------------

# --------------------------------------------------------------------
#
#  Rule: "BuildingEpicPsd()"
#
#

#
#  Rule: "EpicMakeTargets()"
#

hw sim $(MAKE_TARGET):: $(PSD).epic

#
#  Rule: "EpicCvCopy()"
#

hw $(MAKE_TARGET):: $(PSD).cnvendian.c
hw sim $(MAKE_TARGET):: $(PSD).cvcopy.c

$(PSD).cvcopy.c: $(PSD).epic $(PSD).allcv.h $(PSD).tgtex.h

	@echo "=========================================================="
	@echo "   Generating cvcopy functions"
	@echo "=========================================================="

	$(RM) $@

	$(EP_CONTIG) $(PSD) $@ $(PSD).allcv.h $(PSD).tgtex.h

$(PSD).cnvendian.c: $(PSD).epic $(PSD).global.h $(PSD).allcv.h \
	$(PSD).tgtex.h

	@echo "=========================================================="
	@echo "   Generating CV endian conversion code"
	@echo "=========================================================="

	$(RM) $(CNV_ENDIAN_FILES)

	$(CREATE_CNV_ENDIAN_INPUT) $(PSD).cnvendian.input.c \
		$(PSD).global.h $(PSD).allcv.h $(PSD).tgtex.h

	$(ENDIAN_CONVERTER) -i $(PSD).cnvendian.input.c -h $(PSD).cnvendian.private.h -ha $(PSD).cnvendian.api.h -hg $(PSD).cnvendian.globalvar.h -o $(PSD).cnvendian.c $(EPIC_INCLUDES) $(ENDIAN_CONVERTER_FLAGS) $(ENDIAN_EFLAG) -pre cv_cnv_endian_ -no_inc

clean::
	$(RM) $(CNV_ENDIAN_FILES) $(PSD).cvcopy.c

# --------------------------------------------------------------------

# ====================================================================

#
#
#
#
#
#

# ====================================================================
#
#  This dependency line is found in all makefiles.  $(MAKE_TARGET)
#     should be defined in the local Imakefile.
#
# ====================================================================

all $(MAKE_TARGET):: $(ALL_OBJS)

# ====================================================================

